apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
  name: my-nginx
spec:
  # Image specifies when the package that shall be installed
  # is found at.
  image: <your-package-url-goes-here>
