apiVersion: apps/v1
kind: Deployment
metadata:
  name: "my-cool-name"
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: "my-cool-name"
  annotations:
    package-operator.run/phase: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: "my-cool-name"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: "my-cool-name"
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
