apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: nginx
spec:
  scopes:
  - Namespaced
  phases:
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      type: object
      properties:
        banana:
          type: string
      x-kubernetes-preserve-unknown-fields: true
  filter:
    conditions:
    - name: config_banana_bread
      expression: '.config.banana == "bread"'
    paths:
    - expression: 'cond.config_banana_bread'
      glob: 'subfolder/**'
test:
  template:
  # Tests files are included if config.banana == "bread".
  - name: condition-true
    context:
      config:
        banana: bread
  # Tests files are excluded if config.banana != "bread".
  - name: condition-false
    context:
      config:
        banana: no-bread